GET http://localhost:3001/employees/

###

GET http://localhost:3001/employees/2

### 
POST http://localhost:3001/employees HTTP/1.1
Content-Type: application/json

{
    "firstName":"Ericson",
    "lastName":"Hernandez",
    "phone":"1231212",
    "address":"Catiry",
    "departmentId":1
}

###
PUT http://localhost:3001/employees/2 HTTP/1.1
Content-Type: application/json

{
    "firstName": "Jane",
    "lastName": "Smith",
    "phone": "555-5678-3421",
    "address": "456 Oak St",
    "departmentId": 1
}


### 
DELETE http://localhost:3001/employees/15 HTTP/1.1
Content-Type: application/json


########################## departments 

GET http://localhost:3001/departments

###
POST http://localhost:3001/departments HTTP/1.1
Content-Type: application/json

{
    "name":"Development"
}
